spring.application.name=backend-spring
spring.config.import=optional:file:./src/main/resources/application-local.properties
server.port=8090

spring.datasource.url=jdbc:h2:file:./data/expense-tracker
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
debug=false
logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.boot.autoconfigure=INFO

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.org.springframework.web=INFO

openai.api-key= 
openai.model=${OPENAI_MODEL:gpt-5.2}
